# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/AttributeCloner.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: 1.0.$(Build.BuildId)

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-c $(buildConfiguration) --no-build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    nobuild: true
    versioningScheme: byBuildNumber
    packagesToPack: '$(project)'
    
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet'
    versioningScheme: byBuildNumber